include: package:pedantic_mono/analysis_options.yaml
analyzer:
  exclude:
    - lib/gen/**
    - protos/**
    - build/**
    - android/**
    - ios/**
linter:
  rules:
    unnecessary_await_in_return: false

